    on: push
    jobs:
      sms-test:
        runs-on: self-hosted
        steps:
        - name: Notification
          uses: twilio-labs/actions-sms@v1
          with:
            fromPhoneNumber: ${{ secrets.FROM_NUMBER }}
            toPhoneNumber: ${{ secrets.TO_NUMBER }}
            message: 'Hello from Twilio'
          env:
            TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
            TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
            TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
